sudo: false
language: python
python: 3.5

install: pip install -e .[test]

script: py.test tests.py

branches:
    only:
        - master

cache:
  directories:
    - $HOME/.cache/pip

notifications:
  email: false
