sudo: false
language: python
python: 3.5

install: python setup.py develop

script: py.test tests.py

branches:
    only:
        - master

cache:
  directories:
    - $HOME/.cache/pip

notifications:
  email: false
